title:              Deveolper Joon
email:              msj3381@gmail.com
description:        개발자 지망생의 잡다한 지식들
author:             Dal Joon
baseurl:            ""
url:                "https://msj3381.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    msj3381
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
